modLoader="javafml"
loaderVersion="[43,)"
issueTrackerURL=""
displayURL="https://minecraft.curseforge.com/projects/hungergovroom" 
logoFile="vroom_icon.png"
authors="Untrustedlife"
license="GPLv3"

[[mods]]
    modId="hungergovroom"
    version="1.0"
    displayName="Hunger Go Vroom a KubeJS script"
    description="This mod simply makes you get hungry much faster. And makes you hungry after sleeping."
    credits="Vicc for the idea."

[[dependencies.hungergovroom]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.19.2,)"
    ordering="NONE"
    side="BOTH"

[[dependencies.hungergovroom]]
    modId="kubejs"
    mandatory=true
    versionRange="[1902.6.2-build.73,)"
    ordering="NONE"
    side="BOTH"